Module6 task1
htmlacademy-react/116214-six-cities-10 pull request #8
Opened 2022-07-28 01:39 UTC by vtivadze

2022-07-29 22:04 UTC, sahaviev commented on project/src/components/city-list/city-list.tsx
> +            // onClick={clickHandler.bind(null, city)}
Здесь не нужно использовать bind.
Тебе нужно получить доступ городу, для этого нужно создать компонент CityCard или можно даже Card.
Именно его ты будешь отрисовывать в этом цикле.
В компонент ты передаешь city и туда же функцию через пропс onClick={handleCardClick}.
Поскольку компонент знает о city, в обработчике события на onClick внутри этого компонента ты сможешь передать наружу нужны city.name например так:
```
const Card = ({ city, onClick }: Props) => {
const handleClick = () => {
    onClick(city.name);
};
```

2022-07-29 22:05 UTC, sahaviev commented on project/src/components/city-list/city-list.tsx
> +    // How to avoid using DOM
Как избежать использования DOM написал ниже. В целом ты молодец что задался этим вопросом.
Напрямую использовать DOM-элементы и получать из него значения считается плохой практикой.

2022-07-29 22:07 UTC, sahaviev commented on project/src/components/map/map.tsx
> -    if (map) {
Все же лучше проверить:
```
if (!map){
  return;
}
```
А внизу убрать эти проверки на `map && ...`

2022-07-29 22:10 UTC, sahaviev commented on project/src/components/map/map.tsx
> +    // return () => markerGroup?.clearLayers();
<img width="471" alt="image" src="https://user-images.githubusercontent.com/1573252/181851643-a5041a3b-24f5-40f1-90e5-57e22bbdebef.png">

Напиши так. Будет работать без ошибок =)

2022-07-29 22:14 UTC, sahaviev commented on project/src/components/map/map.tsx
> +    // return () => markerGroup?.clearLayers();
Здесь важно понять следующее: 
сокращенная форма записи `return () => markerGroup?.clearLayers();` возвращает в итоге markerGroup, а useEffect ожидает сигнатуру функции которая не будет ничего возвращать. Твоя функция это тоже что и:
```
return () => {
   return markerGroup?.clearLayers();
}
```
Лично я не люблю и почти не использую нигде сокращенные функции в одну строку и всегда явно пишу со скобками. Так безопаснее и нагляднее.

2022-07-29 22:17 UTC, sahaviev commented on project/src/hooks/useMap.tsx
> +  const sampleCity = offers.find((offer) => offer.city.name === city);
Это ты зря сюда засунул.
Ты в итоге ограничиваешь себя в переиспользовании хука useMap.
Тебе этот код нужен только для того чтобы получить sampleCity у которого ты берешь только lon/lat координаты.
Передавай в хук уже готовый объект с координатами без информирования его о городе.

2022-07-29 22:21 UTC, sahaviev commented on project/src/store/action.ts
> +}));
Здесь что-то не то происходит. Экшен называется getOffers, а параметры city - это ошибка и так нельзя слепо копировать!
Обычно экшены не должны ничего возвращать. Они меняют что-то в state. У тебя же название экшена getOffers. Название которое начинается с get подразумевает что функции что-то вернет.

2022-07-29 22:22 UTC, sahaviev commented on project/src/store/reducer.ts
> +    .addCase(getOffers, (state, action) => {
То что твой экшен делает: фильтрует офферы для города который ты передал в action. 
Лучше его назвать setFilteredByCityOffers.

2022-07-29 22:23 UTC, sahaviev commented on project/src/utils.ts
> +export const getActiveOffers = (offers: Offer[], city: string) =>
Это не активные офферы. Это офферы конкретного города который ты указал вторым параметром, поэтому нужно назвать функцию: **getCityOffers**.

2022-07-29 22:25 UTC, sahaviev requested changes
Разворачиваю. Много замечаний. Лучше все их поправить тут.
Ничего плохого в этом нет! У тебя еще дофига консультаций и проверок.
Не переживай, непонятные моменты завтра обговорим.

2022-07-29 23:58 UTC, vtivadze commented on project/src/components/city-list/city-list.tsx
> +            // onClick={clickHandler.bind(null, city)}
Ispravil...

2022-07-30 09:29 UTC, sahaviev approved these changes
Молодец! Очень быстро все поправил!

2022-07-30 09:30 UTC, merged